### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by stuartaccent** [celery/django-celery-results#1]
Hi. I was just wondering if you plan on creating any migrations for this project.

Thanks Stuart

**Comment by astronouth7303** [comment]
Yes please. These are a must now.

**Comment by auvipy** [comment]
you could do that and send a PR which I will merge ;)

**Comment by millin** [comment]
@auvipy welcome ;)
All looks fine, but I'm not sure. Need check on real db

**Comment by stuartaccent** [comment]
cheers to you both :)
