### ISSUE TITLE
Use multiple Database Backends with celery

### ISSUE THREAD

**Issue by NotANormalNerd** [celery/django-celery-results#10]
Is it possible to use the django-celery-results on a Django installation and the database backend backend on a worker or are they incompatible?
Is it possible to configure them to be compatible?

Or would it be better to have a custom table to share results?

The problem that arises when just using celery and the database backend on the django end is that it will bypass all the nice django features and optimizations. As well as not being noticed by the debug-toolbar.

**Comment by mheppner** [comment]
If you're creating a Django project that integrates with Celery, you'll want to just deploy your entire project on each worker node. Each node will have a copy of Django, but it obviously wouldn't be running under WSGI. Each Celery worker can then use the models provided in `django-celery-results` and the same database connection provided by Django. I'm not sure what you would gain by using the pure database backend on each worker and only `django-celery-results` on your running WSGI Django app.

**Comment by arcivanov** [comment]
I need this so I'll implement this.

**Comment by NotANormalNerd** [comment]
I think the idea here is to have a multitude of decoupled projects and therefore tasks that are triggered through a django interface but are independetly deployed. Not only for django jobs, like sending mail or updating the database from a different source (e.g. SVN) but also for other jobs that run on different machines, 

Implementing a custom result backend is possible but i think this should be quite a common usecase. You still need some custom code if you want to have persistent and extended results but for the basics of passed/failed tasks with some background info, the celery result backend is fine.

@arcivanov I would be really grateful to see your implementation when its finished.

**Comment by arcivanov** [comment]
I'll submit a PR, naturally. I suspect if you use routers it shouldn't be a big deal, I haven't really looked though yet.

**Comment by jezdez** [comment]
I concur with @mheppner: the django-celery-results app is structured in such a way that you would deploy the same code base on both your web nodes as well as the worker nodes. There is no need to fully isolate those two from each other especially since it's a common pattern to use data models from your project in tasks that the workers process. I would even go so far that having the django-celery-results available in the web app is useful if you want to inspect the results of a particular job after it has run.

**Comment by auvipy** [comment]
Could you check the master if it's already supported?
