### ISSUE TITLE
Nothing shown in django admin results, results only in flower

### ISSUE THREAD

**Issue by GabLeRoux** [celery/django-celery-results#102]
Hello there,  
I just gave this a try and I can't figure out why I get no results in the admin.

Here's what I tried:
1. Generate a project from [django cookiecutter](https://github.com/pydanny/cookiecutter-django) so I get Celery with Redis already setup.
2. Install `django-celery-email`, add to installed apps and set `settings.EMAIL_BACKEND`
3. Install `django-celery-results`, add to installed apps and setup [as described in the documentation](http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend)

Here are exact commands to reproduce the issue:

```bash
git clone git@github.com:GabLeRoux/django-celery-results-with-redis-example.git
cd django-celery-results-with-redis-example
# checkout the specific commit of the project at the time of creation of this issue
git checkout ace6fcd5ad0099d1054bd42d275f974ef99b81cf
docker-compose up -d
docker-compose logs -f &
# wait for everything to be up, then send a test email that will actually be queued with celery
docker-compose run --rm django python manage.py sendtestemail --admin
```

Email is successfully sent and does go through the queue using celery. Open a shell and verify the data:

```bash
docker-compose run --rm django python manage.py shell_plus
```
```python
TaskResult.objects.all()
```

> Out[1]: <QuerySet []>

**It's empty, that's the problem 😢**

The result is shown in flower correctly:

![image](https://user-images.githubusercontent.com/1264761/59809353-30228e00-92ce-11e9-9766-497804037834.png)

The email is definitely sent correctly too

![image](https://user-images.githubusercontent.com/1264761/59809391-534d3d80-92ce-11e9-8f6f-59b59501ba3b.png)

The result backend doesn't seem to be used correctly or there's something I'm missing here:

![image](https://user-images.githubusercontent.com/1264761/59809418-70820c00-92ce-11e9-9c31-70d502c1177e.png)

## Related settings

```python
In [2]: settings.CELERY_BROKER_URL
Out[2]: 'redis://redis:6379/0'

In [3]: settings.CELERY_RESULT_BACKEND
Out[3]: 'django-db'

In [4]: settings.EMAIL_BACKEND
Out[4]: 'djcelery_email.backends.CeleryEmailBackend'

In [5]: settings.INSTALLED_APPS
Out[5]:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'crispy_forms',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'rest_framework',
 'django_celery_beat',
 'django_celery_results',
 'djcelery_email',
 'example.users.apps.UsersConfig',
 'debug_toolbar',
 'django_extensions']
```

**Comment by PaszaVonPomiot** [comment]
I confirm the issue. It shows me the results in Flower but not in django-celery-results. The fix was to add `-E` switch to celery worker. This is not clearly described in docs and should be added.

systemd exec command would look like this:
```
ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} -E ${CELERYD_OPTS}'
```

**Comment by larsrei** [comment]
Hi,
I have the same problem, the Task Results in the table are missing. I am not using flower. Only django, django-celery-results and database (try sqlite and mariadb).

# CELERY STUFF
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Berlin'
DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH=191

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modules',
    'guardian',
    'rest_framework',
    'rest_framework.authtoken',
    'django_celery_results',
    'rangefilter',
    'import_export',
]

Table was migrated without problems. The celery task run and work correctly. But no entry in database table. I tested with local sqlite and mariadb.
So now I read the switch -E not sure what you mean with this. I only start celery worker in my project.


best regards,
Lars

**Comment by PaszaVonPomiot** [comment]
In my start script there is -E switch when I start celery worker try it:

ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
   -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
   --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} -E 
${CELERYD_OPTS}'







------ Original Message ------

**Comment by larsrei** [comment]
I tested it on some systems (ubuntu 19.04, RHEL (GNU/Linux 3.10.0-1062.1.2.el7.x86_64 Linux) ) , with different databases (sqlite, mariadb) but always same problem. Celery result is not written to database. the switch -E is not helping me.
Some tips how I can debug further ?

**Comment by PaszaVonPomiot** [comment]
I don't have any more ideas, sorry.

------ Original Message ------

**Comment by kowalej** [comment]
@larsrei  - not sure how you were running Celery, but I had the same problem when testing, it was do to not running Celery worker - I was only running the scheduler.

First run: 
`celery -A <proj> worker`
Then:
`celery -A <proj> beat -l info`

**Comment by larsrei** [comment]
Hi @kowalej,
in our development environment we are running celery local. Here we only run worker like your first run. In production we need both beat and worker. Here we use supervisor.
Development is on Ubuntu, production on RHEL. On both it's not working. At the moment we have no debugging idea.

**Comment by johnthealy3** [comment]
Put the following in settings.py and django-celery-results should work with one TaskResult per email:

CELERY_EMAIL_TASK_CONFIG = {'ignore_result': False}
CELERY_EMAIL_CHUNK_SIZE = 1

It took me a long time to figure this out even though it is (abstractly) mentioned in the README for django-celery-email.

**Comment by ktzalas** [comment]
Hello everyone,

I had a similar scenario with an app deployed on kubernetes with this problem as as well, in my case I am using celery with redis as the broker.  My problem was in my configuration ( almost always is  😄 ) were I used redis in both the broken and result DB.

Below is my celery config from `system.py`, maybe this can help someone with a similar issue. 

This is the old not working config.

```
CELERY_BROKER_URL = os.getenv('REDISADDR','redis://localhost:6379')
CELERY_RESULT_BACKEND = os.getenv('REDISADDR','redis://localhost:6379')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('TIME_ZONE','Europe/Athens')
```

This is the working config.
```
CELERY_BROKER_URL = os.getenv('REDISADDR','redis://localhost:6379')
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('TIME_ZONE','Europe/Athens')
```

**Comment by auvipy** [comment]
> This is the working config.
> 
> ```
> CELERY_BROKER_URL = os.getenv('REDISADDR','redis://localhost:6379')
> CELERY_RESULT_BACKEND = 'django-db'
> CELERY_ACCEPT_CONTENT = ['application/json']
> CELERY_TASK_SERIALIZER = 'json'
> CELERY_RESULT_SERIALIZER = 'json'
> CELERY_TIMEZONE = os.getenv('TIME_ZONE','Europe/Athens')
> ```

based on this I think we should close this issue

**Comment by auvipy** [comment]
> I confirm the issue. It shows me the results in Flower but not in django-celery-results. The fix was to add `-E` switch to celery worker. This is not clearly described in docs and should be added.
> 
> systemd exec command would look like this:
> 
> ```
> ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
>   -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
>   --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} -E ${CELERYD_OPTS}'
> ```

is this contributed to celery docs?

**Comment by PaszaVonPomiot** [comment]
I haven't added anything to docs. I think someone more knowledgable in celery should review this before adding anything to docs.

**Comment by MatejMijoski** [comment]
> I confirm the issue. It shows me the results in Flower but not in django-celery-results. The fix was to add `-E` switch to celery worker. This is not clearly described in docs and should be added.
> 
> systemd exec command would look like this:
> 
> ```
> ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
>   -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
>   --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} -E ${CELERYD_OPTS}'
> ```

I can also confirm that adding -E enabled `django-celery-results` to capture the events and show them in the admin tables.

**Comment by chrispijo** [comment]
For me it also turned out that adding the -E flag enabled the results to be included in the backend database.

**Comment by vladox** [comment]
What about the CELERY_CACHE_BACKEND setting is not that supposed to be used when using REDIS as CELERY_BROKER_URL?

**Comment by auvipy** [comment]
> What about the CELERY_CACHE_BACKEND setting is not that supposed to be used when using REDIS as CELERY_BROKER_URL?

can you please elaborate?

**Comment by APouzi** [comment]
> django-db'

Im sorry, I am a total noob with Linux systems and I am using Bash on windows. I tried putting thing into my venv and got back "bash: -c: command not found", "which bash" and got a "/usr/bin/bash" and change those variables to match that and I am still getting this issue. It doesn't work outside of Venv either. 
I can't seem to find the solution to where I am suppose to put this to fix the issue.

**Comment by leemurus** [comment]
> Hello everyone,
> 
> I had a similar scenario with an app deployed on kubernetes with this problem as as well, in my case I am using celery with redis as the broker. My problem was in my configuration ( almost always is 😄 ) were I used redis in both the broken and result DB.
> 
> Below is my celery config from `system.py`, maybe this can help someone with a similar issue.
> 
> This is the old not working config.
> 
> ```
> CELERY_BROKER_URL = os.getenv('REDISADDR','redis://localhost:6379')
> CELERY_RESULT_BACKEND = os.getenv('REDISADDR','redis://localhost:6379')
> CELERY_ACCEPT_CONTENT = ['application/json']
> CELERY_TASK_SERIALIZER = 'json'
> CELERY_RESULT_SERIALIZER = 'json'
> CELERY_TIMEZONE = os.getenv('TIME_ZONE','Europe/Athens')
> ```
> 
> This is the working config.
> 
> ```
> CELERY_BROKER_URL = os.getenv('REDISADDR','redis://localhost:6379')
> CELERY_RESULT_BACKEND = 'django-db'
> CELERY_ACCEPT_CONTENT = ['application/json']
> CELERY_TASK_SERIALIZER = 'json'
> CELERY_RESULT_SERIALIZER = 'json'
> CELERY_TIMEZONE = os.getenv('TIME_ZONE','Europe/Athens')
> ```

Yeah, the main point that `CELERY_RESULT_BACKEND = 'django-db'`. In celery worker and web should be 'django-db' value for result backend. Sample of my project https://github.com/leemurus/crawler
