### ISSUE TITLE
any plans or interest in replicating the task status json response from django-celery?

### ISSUE THREAD

**Issue by nthall** [celery/django-celery-results#103]
I'm wondering if the omission of the django-celery feature for returning json data about task status in this project is intentional or not. Seems like this is the logical place for that functionality. If it's welcome I would be glad to add it but if it's omitted intentionally I will roll my own replacement and live with that.

**Comment by auvipy** [comment]
I think this is a missing feature

**Comment by nthall** [comment]
I've finally gotten around to working on this for a PR, but I'm having trouble with running tox - specifically postgres issues. Any pointers on dealing with that?

**Comment by nthall** [comment]
I have resolved issues with running tox -- the most pressing one was that my pg_hba.conf wasn't properly configured to allow the connection defined in t/proj/settings.py.  Secondarily, on Ubuntu 18.04, extra steps are needed to make python3.5 available to tox.

So, now I have actual debugging to do, just wanted to leave these notes here for reference.

**Comment by nthall** [comment]
Hi again, I've finally had more cycles to sort this out. Everything works and the tests for the new (old) functionality pass. The only tests failing in tox right now is the `apicheck` because my virtualenv is running python2.7, but sphinx_celery requires sphinx>=2.0.0, which doesn't support python2.7. Should I submit even though this test fails?

**Comment by liquidpele** [comment]
You can submit the PR, but we can't merge it unless all tests are passing.  I recently fixed several of the tests though, so merge in master and see if that helps.

**Comment by nthall** [comment]
Ok, I will make sure everything is tidy and submit soon. Maybe it will pass in a different environment!
