### ISSUE TITLE
still can't solve the MySQL error

### ISSUE THREAD

**Issue by weiziyoung** [celery/django-celery-results#112]
After I set it in the settings.py like this:
```
DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH=191
```
I still get the same error:
```
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```
Can you explain further that where should I add the sentence:`DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH=191`?

**Comment by auvipy** [comment]
this is now solved in master.
