### ISSUE TITLE
Cleanup task times out

### ISSUE THREAD

**Issue by asfaltboy** [celery/django-celery-results#117]
The `celery.backend_cleanup` task is super slow reaching our configured soft time limit of 15 minutes. The slow query is the delete and update queries called by `TaskResultManager.delete_expired()`:

https://github.com/celery/django-celery-results/blob/64315751dbe7eac8b3276acb8ed56db2add71b74/django_celery_results/managers.py#L173-L177

We can increase the limit for the cleanup task (by updating the `soft_time_limit` property of the task), but that will only be a bandaid rather than a long term solution.

I have reproduced a simplified case of this issue by creating 2mil results locally (only setting uuid() and using default of the model), setting 1mil to an older date and running the query:

```python
>>> from datetime import datetime, timedelta
>>> from django.db import connection
>>> from celery import states, uuid
>>> from django_celery_results.models import  *
>>> [TaskResult(task_id=uuid()) for _ in range(1_000_000)]
>>> [TaskResult(task_id=uuid()) for _ in range(1_000_000)]
>>> othermil = TaskResult.objects.filter(id__gt=1_000_000)

>>> old_date = datetime.now() - timedelta(days=5)
>>> othermil.update(date_done=old_date)

>>> print("\n".join(f"{q['sql'][:300]}: {q['time']}" for q in connection.queries))

INSERT INTO "django_celery_results_taskresult" ("task_id", "task_name", "task_args", "task_kwargs", "status", "worker", "content_type", "content_encoding", "result", "date_created", "date_done", "traceback", "hidden", "meta") VALUES ('33efa9af-08b3-4dc6-8808-4597f1da2b17', NULL, NULL, NULL, 'PEND...: 203.467
INSERT INTO "django_celery_results_taskresult" ("task_id", "task_name", "task_args", "task_kwargs", "status", "worker", "content_type", "content_encoding", "result", "date_created", "date_done", "traceback", "hidden", "meta") VALUES ('0f9d897a-bebb-42b3-ba24-f80061c97c95', NULL, NULL, NULL, 'PEND...: 214.064
UPDATE "django_celery_results_taskresult" SET "date_done" = '2019-10-16T13:19:12.314815+00:00'::timestamptz WHERE "django_celery_results_taskresult"."id" >= 1000002: 137.222

# and after running: TaskResult.objects.delete_expired(86_400)

UPDATE "django_celery_results_taskresult" SET "hidden" = true WHERE "django_celery_results_taskresult"."date_done" < '2019-10-20T18:41:52.125578+00:00'::timestamptz: 149.066
DELETE FROM "django_celery_results_taskresult" WHERE "django_celery_results_taskresult"."hidden" = true: 3.387
```

The UPDATE query takes over 2 minutes, the DELETE is pretty fast.

In our production case we're talking slightly bigger dataset than this, with significantly more data in other fields (e.g metadata of `chord_unlocks` to collect multiple tasks that were chained into a group). I just timed the "update portion" of the `delete_expired` task manually, and it took over an hour and a half:
```python
In [20]: %time expired_update = TaskResult.objects.get_all_expired(expires).update(hidden=True)
CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 1h 33min 46s
In [22]: TaskResult.objects.filter(hidden=True).delete()
Out[22]: (1977820, {'django_celery_results.TaskResult': 1977820})
```

Is it there anything we can do to help debug the issue, what should we consider to improve the database operation? Can we consider removing the index on mtime, or use a partial index maybe?
count

**Comment by liquidpele** [comment]
What delete query?  What DB?  What cleanup task?  This is not a good issue report.  

https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines

**Comment by asfaltboy** [comment]
Thanks @liquidpele, my bad for leaving a lazy stub of a bug. I added a bit more detail above, can you check if there's anything else you would like to see?
