### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by Lingghh** [celery/django-celery-results#123]
When will the new version be released?
Will the next version add ``worker`` field in ``TaskResult``?

**Comment by maxmalysh** [comment]
+1. This change is 9 months old and it's still not in pypi.

**Comment by maxmalysh** [comment]
@auvipy thanks you for maintaining the project! 

Could you release a new version, please?

Also, I've ported two small features from the old project (`django-celery`):
PR https://github.com/celery/django-celery-results/pull/125 — Make `TaskResult` read-only by default
PR https://github.com/celery/django-celery-results/pull/124 — Add `worker` to `list_filter`

**Comment by intgr** [comment]
Please close this issue, these were released in February with 1.2.0
