### ISSUE TITLE
celery results table

### ISSUE THREAD

**Issue by superandrew** [celery/django-celery-results#127]
Hi, to my huge surprise, after days passed trying to understand why my results weren't stored, I noticed they are, but not in `django_celery_results_taskresult` as I expected but instead in `celery_taskmeta`.

Is this correct? Is there a reason for this? I couldn't find it on the documentation.

Thanks

**Comment by Ixiodor** [comment]
celery_taskmeta is the "default" table created on a classic db_backend.
That means you didn't set Celery backend "backend='django-db'" but isteand you provvided your DB url/user/password for DB connection

**Comment by ZviBaratz** [comment]
@auvipy Can this be closed? 
Also, I hope tagging you randomly is helpful rather than intrusive. I just figured trying to clean up issues and PRs could be good, and I don't have the required permissions.

**Comment by auvipy** [comment]
thanks
