### ISSUE TITLE
Django 3.0 Support

### ISSUE THREAD

**Issue by Palisand** [celery/django-celery-results#131]
Does this package support Django 3.0? Has it been tested on the latest version?

**Comment by auvipy** [comment]
you can try and report

**Comment by kubami** [comment]
FWIW, I have been using this with Django 3.0 (currently 3.0.5), in production without any problems.

**Comment by Palisand** [comment]
We've only begun using it. So far so good. We're not experiencing https://github.com/celery/django-celery-beat/issues/323.

**Comment by Palisand** [comment]
https://github.com/celery/django-celery-results/pull/145
