### ISSUE TITLE
Worker status in the admin

### ISSUE THREAD

**Issue by psychok7** [celery/django-celery-results#15]
@ask In django-celery we could see the active workers in the admin, with this new package is there a way for that as well?

**Comment by jezdez** [comment]
While I wasn't around when @ask decided to split up django-celery into multiple smaller apps I think it's fair to say that django-celery shows a higher implementation complexity and adding some of this functionality into this app again would be a disservice to the intention of keeping things simple.

**Comment by psychok7** [comment]
@jezdez i am thinking of trying out this app that you just released https://github.com/jezdez/django-celery-monitor . I am assuming it shows the active workers in the admin (i haven't tried it yet).

**Comment by jezdez** [comment]
@psychok7 Yep, it's a port of the monitoring feature from django-celery, so you'll see tasks and workers states based on Celery events. It's less featured than [Flower](http://flower.readthedocs.io/) though.

**Comment by psychok7** [comment]
@jezdez thanks, i am about to try it right now.
