### ISSUE TITLE
Incompatibility with celery v4.4.4

### ISSUE THREAD

**Issue by solarissmoke** [celery/django-celery-results#150]
Celery v4.4.4 [changed the signature](https://github.com/celery/celery/commit/0463bff0530b8aef8d31bd8039f245735295db59) of the `set()` method for results backends, which means that you currently get the following error when using celery 4.4.4:

```
set() takes 3 positional arguments but 4 were given
```

So we need to update that method here to accept the 4th argument.

**Comment by shield007** [comment]
I'm also seeing this erorr, just tested with master so still a issue. Guess it needs the PR's merging in.
