### ISSUE TITLE
RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated

### ISSUE THREAD

**Issue by rmk135** [celery/django-celery-results#160]
Hey everybody,

I see this warning currently when running tests:

> /usr/local/lib/python3.8/site-packages/django_celery_results/models.py:91
>   /usr/local/lib/python3.8/site-packages/django_celery_results/models.py:91: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().

```
Python 3.8
Django 3.1.1
```

Seems like ``ugettext_lazy()`` can be used instead of ``gettext_lazy()`` without any issues for any Python 3 and Django 2.2.

**Comment by dmartin** [comment]
This looks like it was fixed a while ago, there just hasn't been a new release since then: https://github.com/celery/django-celery-results/commit/069f57bd79459fd51ea36776a13834d47bb9db2b

Any chance of a new point release soon, if only to silence these warnings?

**Comment by niksubramanian** [comment]
Tagging @auvipy here - auvipy: if you need any help for a release, I'd be happy to help to take some burden off your shoulders!

**Comment by rmk135** [comment]
I'm positive to make a PR too. Let me know if help is appreciated.

**Comment by niksubramanian** [comment]
Small bump - perhaps @thedrow is the right person to talk to for this? I can imagine that with the v5 release of celery that there's quite a lot in the backlog, but I'm happy to help for a release (e.g. writing the release notes).

**Comment by Overdrivr** [comment]
This is crowding our logs as well.

**Comment by pkrefta** [comment]
My logs are getting crowded too.

**Comment by thedrow** [comment]
Hi everyone.
I'm working on 5.0.2 which contains very critical fixes. Please bear with us.

I'm going to focus on our Django integrations next.

**Comment by niksubramanian** [comment]
Thanks for the update and the help on this @thedrow !

**Comment by warmwaffles** [comment]
@thedrow thanks for the update. Do you need help with anything?

**Comment by thedrow** [comment]
We need a dedicated person to maintain the Django integrations.
It's usually not much work.

**Comment by pkrefta** [comment]
Temporarily it's possible to mute those warnings by using this snippet
```
import warnings
from django.utils.deprecation import RemovedInDjango40Warning

if DEBUG:
    warnings.simplefilter('ignore', category=RemovedInDjango40Warning)
```

**Comment by rmk135** [comment]
@pkrefta , is it possible to mute just a specific warning from a particular library / line?

**Comment by pkrefta** [comment]
Yes - it's possible.  You have to use different method and ``module`` keyword arguments as it's shown here https://stackoverflow.com/questions/3920502/how-to-suppress-a-third-party-warning-using-warnings-filterwarnings

**Comment by niksubramanian** [comment]
@thedrow regarding a dedicated maintainer - perhaps it's worth making a pinned issue with a bit more information on what's involved in maintaining this library?

**Comment by auvipy** [comment]
isn't it fixed with the new release?

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-results/commit/069f57bd79459fd51ea36776a13834d47bb9db2b released long ago
