### ISSUE TITLE
Dependency problem with celery 5.0

### ISSUE THREAD

**Issue by AMontagu** [celery/django-celery-results#162]
Hello !

I am upgrading to celery 5.0 and everything was okay until django-celery-results. It seem that their subdependencies are not comptabile about vine. I am using pipenv.

This is the output of pipdeptree for django celery results:
```
django-celery-results==1.2.1
  - celery [required: >=4.4,<5.0, installed: 4.4.7]
    - billiard [required: >=3.6.3.0,<4.0, installed: 3.6.3.0]
    - kombu [required: >=4.6.10,<4.7, installed: 4.6.11]
      - amqp [required: >=2.6.0,<2.7, installed: 2.6.1]
        - vine [required: >=1.1.3,<5.0.0a1, installed: 1.3.0]
      - importlib-metadata [required: >=0.18, installed: 1.7.0]
        - zipp [required: >=0.5, installed: 3.1.0]
    - pytz [required: >dev, installed: 2020.1]
    - vine [required: ==1.3.0, installed: 1.3.0]
```

Seem like django-celery-results does not support celery 5.0. 

the output ok pipenv lock:
```
ERROR: Could not find a version that matches vine==1.3.0,==5.0.0 (from celery[redis]==4.4.7->-r /tmp/pipenv7iua3a08requirements/pipenv-zb6tz0x4-constraints.txt (line 4))
Tried: 0.9.0, 0.9.0, 0.9.1, 0.9.1, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.1.0, 1.1.0, 1.1.1, 1.1.1, 1.1.2, 1.1.2, 1.1.3, 1.1.3, 1.1.4, 1.1.4, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 5.0.0, 5.0.0
Skipped pre-versions: 5.0.0a1, 5.0.0a1
There are incompatible versions in the resolved dependencies:
  vine==1.3.0 (from celery[redis]==4.4.7->-r /tmp/pipenv7iua3a08requirements/pipenv-zb6tz0x4-constraints.txt (line 4))
  vine==5.0.0 (from amqp==5.0.1->kombu==5.0.2->celery[redis]==5.0.0->-r /tmp/pipenv7iua3a08requirements/pipenv-zb6tz0x4-constraints.txt (line 4))
```

**Comment by AMontagu** [comment]
Look like it's in the celery [breaking changes](https://docs.celeryproject.org/en/master/changelog.html):
- Breaking Change Remove AMQP result backend (#6360).

What can we use to replace it and have visibility on task result in celery 5

**Comment by 3skr0** [comment]
same issue here

**Comment by 3skr0** [comment]
On pip, it looks like the package is not release yet.

You can add below to your requirements file 
`git+https://github.com/celery/django-celery-results/zipball/master@ed94080cea3d68a38f9ff048657a37b08e74fc35#egg=django-celery-results
`
Or 
`
pip install -e https://github.com/celery/django-celery-results/zipball/master@ed94080cea3d68a38f9ff048657a37b08e74fc35#egg=django-celery-results
`

**Comment by waynegrigsby** [comment]
Using Poetry and can't install django_celery_results without downgrading Celery from v5.0:

```
Because django-celery-results (1.2.1) depends on celery (>=4.4,<5.0)
 and no versions of django-celery-results match >1.2.1,<2.0.0, django-celery-results (>=1.2.1,<2.0.0) requires celery (>=4.4,<5.0).
So, because sf-financial-edge depends on both celery (^5.0.1) and django-celery-results (^1.2.1), version solving failed.
```

**Comment by thedrow** [comment]
> Look like it's in the celery [breaking changes](https://docs.celeryproject.org/en/master/changelog.html):
> 
> * Breaking Change Remove AMQP result backend (#6360).
> 
> What can we use to replace it and have visibility on task result in celery 5

That is entirely unrelated.
You're using the Django result backend, not the removed AMQP backend.

**Comment by DaehunGwak** [comment]
> On pip, it looks like the package is not release yet. (Last realaease in februray, the last commit for celery 5, is since a few days)
> 
> You can add below to your requirements file
> `git+https://github.com/celery/django-celery-results.git@ed94080cea3d68a38f9ff048657a37b08e74fc35#egg=django-celery-results `
> Or
> `pip install -e https://github.com/celery/django-celery-results.git@ed94080cea3d68a38f9ff048657a37b08e74fc35#egg=django-celery-results`

The last command doesn't working to me. So i fix like this `pip install -e git+https://github.com/celery/django-celery-results.git@ed94080cea3d68a38f9ff048657a37b08e74fc35\#egg\=django-celery-results`

Thank you for sharing :)

**Comment by fanshuai** [comment]
When will it be officially released? look forward to ~

**Comment by regzon** [comment]
I guess the bug is fixed now (in the latest release)
