### ISSUE TITLE
Unregister TaskResult in Admins

### ISSUE THREAD

**Issue by afsangujarati93** [celery/django-celery-results#166]
I read the documentation but I couldn't find a way to unregister the TaskResult admin. I don't want to display the TaskResult model data on the admin page. 
I tried the following in the django `admin.py` file 
```
from django_celery_results.models import TaskResult
from django_celery_results.admin import TaskResultAdmin
admin.site.unregister(TaskResult)
```

but it gives me the following error: 
```
raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model TaskResult is not registered
```

How else can I not show the TaskResult in the admin page?

**Comment by anuj-gup** [comment]
@afsangujarati93 What's the reasoning behind this?
I'm also facing same issue.
