### ISSUE TITLE
What's the use of 'hidden' field?

### ISSUE THREAD

**Issue by gotounix** [celery/django-celery-results#17]

**Comment by jezdez** [comment]
In the [manager method `delete_expired`](https://github.com/celery/django-celery-results/blob/a9cdb5e8dcffc0cb353086fffb7ea9891b3d12b8/django_celery_results/managers.py#L150-L159) that is used by the Celery backend to cleanup stale results, it will be used to make the query fast by doing only two queries in total: an `UPDATE` query and a consecutive `DELETE` query with those rows that were updated in the first query.
