### ISSUE TITLE
That happens on error

### ISSUE THREAD

**Issue by Ixiodor** [celery/django-celery-results#175]
> [2020-11-23 17:33:18,136: WARNING/ForkPoolWorker-1] /home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py:619: RuntimeWarning: Exception raised outside body: IntegrityError('null value in column "task_id" violates not-null constraint\nDETAIL:  Failing row contains (41, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFhbAAAAVmFsdWVFcnJv..., 2020-11-23 16:33:17.869176+00, Traceback (most recent call last):\n  File "/home/ubuntu/venvs/ea..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGY0ZjVmNTZkLTQ3MzctNGI5NS1h..., gAJOLg==, gAJOLg==, null, null, 2020-11-23 16:33:17.869145+00).\n'):
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 409, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 701, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
>     ret = task.retry(exc=exc, **retry_kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/task.py", line 703, in retry
>     raise_with_context(exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
>     return task._orig_run(*args, **kwargs)
>   File "/var/www/django_projects/earthalytics-api/api_v3/nodes/BuildingsClassification50cm.py", line 38, in execute
>     predictor.predict(input_path, output_path)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/rasterprediction/predictor.py", line 94, in predict
>     labels = inferer.predict(x)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/rasterprediction/backend/inferer.py", line 160, in predict
>     temp[:x.shape[0], :x.shape[1]] = x
> ValueError: could not broadcast input array from shape (3,336,244) into shape (3,336,256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 147, in trigger_callback
>     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 746, in join
>     value = result.get(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 219, in get
>     self.maybe_throw(callback=callback)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 335, in maybe_throw
>     self.throw(value, self._to_remote_traceback(tb))
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 328, in throw
>     self.on_ready.throw(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/vine/promises.py", line 234, in throw
>     reraise(type(exc), exc, tb)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/vine/utils.py", line 30, in reraise
>     raise value
> ValueError: could not broadcast input array from shape (3,336,244) into shape (3,336,256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
>     return self.get(**kwargs), False
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
>     raise self.model.DoesNotExist(
> django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> psycopg2.errors.NotNullViolation: null value in column "task_id" violates not-null constraint
> DETAIL:  Failing row contains (41, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFhbAAAAVmFsdWVFcnJv..., 2020-11-23 16:33:17.869176+00, Traceback (most recent call last):
>   File "/home/ubuntu/venvs/ea..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGY0ZjVmNTZkLTQ3MzctNGI5NS1h..., gAJOLg==, gAJOLg==, null, null, 2020-11-23 16:33:17.869145+00).
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 426, in trace_task
>     I, R, state, retval = on_error(task_request, exc, uuid)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 362, in on_error
>     R = I.handle_error_state(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 165, in handle_error_state
>     return {
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 212, in handle_failure
>     task.backend.mark_as_failure(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 168, in mark_as_failure
>     self.on_chord_part_return(request, state, exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 127, in on_chord_part_return
>     trigger_callback(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 155, in trigger_callback
>     app.backend.chord_error_from_stack(callback, ChordError(reason))
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 254, in chord_error_from_stack
>     return backend.fail_from_current_stack(callback.id, exc=exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 261, in fail_from_current_stack
>     self.mark_as_failure(task_id, exc, exception_info.traceback)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 164, in mark_as_failure
>     self.store_result(task_id, exc, state,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 438, in store_result
>     self._store_result(task_id, result, state, traceback,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 43, in _store_result
>     self.TaskModel._default_manager.store_result(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/managers.py", line 47, in _inner
>     return fun(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/managers.py", line 132, in store_result
>     obj, created = self.using(using).get_or_create(task_id=task_id,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
>     return self._create_object_from_params(kwargs, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
>     obj = self.create(**params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
>     obj.save(force_insert=True, using=self.db)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
>     self.save_base(using=using, force_insert=force_insert,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
>     updated = self._save_table(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
>     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
>     return manager._insert(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
>     return query.get_compiler(using=using).execute_sql(returning_fields)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> django.db.utils.IntegrityError: null value in column "task_id" violates not-null constraint
> DETAIL:  Failing row contains (41, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFhbAAAAVmFsdWVFcnJv..., 2020-11-23 16:33:17.869176+00, Traceback (most recent call last):
>   File "/home/ubuntu/venvs/ea..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGY0ZjVmNTZkLTQ3MzctNGI5NS1h..., gAJOLg==, gAJOLg==, null, null, 2020-11-23 16:33:17.869145+00).
> 
> 
>   warn(RuntimeWarning(
> 
> [2020-11-23 17:33:18,505: WARNING/ForkPoolWorker-1] /home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py:619: RuntimeWarning: Exception raised outside body: DoesNotExist('ChordCounter matching query does not exist.'):
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 409, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 701, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/autoretry.py", line 54, in run
>     ret = task.retry(exc=exc, **retry_kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/task.py", line 703, in retry
>     raise_with_context(exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/autoretry.py", line 34, in run
>     return task._orig_run(*args, **kwargs)
>   File "/var/www/django_projects/earthalytics-api/api_v3/nodes/BuildingsClassification50cm.py", line 38, in execute
>     predictor.predict(input_path, output_path)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/rasterprediction/predictor.py", line 94, in predict
>     labels = inferer.predict(x)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/rasterprediction/backend/inferer.py", line 160, in predict
>     temp[:x.shape[0], :x.shape[1]] = x
> ValueError: could not broadcast input array from shape (3,336,244) into shape (3,336,256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 147, in trigger_callback
>     ret = j(timeout=app.conf.result_chord_join_timeout, propagate=True)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 746, in join
>     value = result.get(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 219, in get
>     self.maybe_throw(callback=callback)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 335, in maybe_throw
>     self.throw(value, self._to_remote_traceback(tb))
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/result.py", line 328, in throw
>     self.on_ready.throw(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/vine/promises.py", line 234, in throw
>     reraise(type(exc), exc, tb)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/vine/utils.py", line 30, in reraise
>     raise value
> ValueError: could not broadcast input array from shape (3,336,244) into shape (3,336,256)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
>     return self.get(**kwargs), False
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
>     raise self.model.DoesNotExist(
> django_celery_results.models.TaskResult.DoesNotExist: TaskResult matching query does not exist.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> psycopg2.errors.NotNullViolation: null value in column "task_id" violates not-null constraint
> DETAIL:  Failing row contains (41, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFhbAAAAVmFsdWVFcnJv..., 2020-11-23 16:33:17.869176+00, Traceback (most recent call last):
>   File "/home/ubuntu/venvs/ea..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGY0ZjVmNTZkLTQ3MzctNGI5NS1h..., gAJOLg==, gAJOLg==, null, null, 2020-11-23 16:33:17.869145+00).
> 
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 426, in trace_task
>     I, R, state, retval = on_error(task_request, exc, uuid)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 362, in on_error
>     R = I.handle_error_state(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 165, in handle_error_state
>     return {
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 212, in handle_failure
>     task.backend.mark_as_failure(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 168, in mark_as_failure
>     self.on_chord_part_return(request, state, exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 127, in on_chord_part_return
>     trigger_callback(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 155, in trigger_callback
>     app.backend.chord_error_from_stack(callback, ChordError(reason))
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 254, in chord_error_from_stack
>     return backend.fail_from_current_stack(callback.id, exc=exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 261, in fail_from_current_stack
>     self.mark_as_failure(task_id, exc, exception_info.traceback)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 164, in mark_as_failure
>     self.store_result(task_id, exc, state,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 438, in store_result
>     self._store_result(task_id, result, state, traceback,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 43, in _store_result
>     self.TaskModel._default_manager.store_result(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/managers.py", line 47, in _inner
>     return fun(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/managers.py", line 132, in store_result
>     obj, created = self.using(using).get_or_create(task_id=task_id,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 576, in get_or_create
>     return self._create_object_from_params(kwargs, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 610, in _create_object_from_params
>     obj = self.create(**params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 447, in create
>     obj.save(force_insert=True, using=self.db)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 753, in save
>     self.save_base(using=using, force_insert=force_insert,
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 790, in save_base
>     updated = self._save_table(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 895, in _save_table
>     results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/base.py", line 933, in _do_insert
>     return manager._insert(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
>     return getattr(self.get_queryset(), name)(*args, **kwargs)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 1254, in _insert
>     return query.get_compiler(using=using).execute_sql(returning_fields)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
>     return super().execute(sql, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
>     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
>     return executor(sql, params, many, context)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
>     raise dj_exc_value.with_traceback(traceback) from exc_value
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
> django.db.utils.IntegrityError: null value in column "task_id" violates not-null constraint
> DETAIL:  Failing row contains (41, null, FAILURE, application/x-python-serialize, binary, gAJjY2VsZXJ5LmV4Y2VwdGlvbnMKQ2hvcmRFcnJvcgpxAFhbAAAAVmFsdWVFcnJv..., 2020-11-23 16:33:17.869176+00, Traceback (most recent call last):
>   File "/home/ubuntu/venvs/ea..., gAJ9cQBYCAAAAGNoaWxkcmVucQFdcQJYJAAAAGY0ZjVmNTZkLTQ3MzctNGI5NS1h..., gAJOLg==, gAJOLg==, null, null, 2020-11-23 16:33:17.869145+00).
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 540, in trace_task
>     return task.__trace__(uuid, args, kwargs, request)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 528, in trace_task
>     I, _, _, _ = on_error(task_request, exc, uuid)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 362, in on_error
>     R = I.handle_error_state(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 165, in handle_error_state
>     return {
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/app/trace.py", line 212, in handle_failure
>     task.backend.mark_as_failure(
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/celery/backends/base.py", line 168, in mark_as_failure
>     self.on_chord_part_return(request, state, exc)
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django_celery_results/backends/database.py", line 112, in on_chord_part_return
>     ChordCounter.objects.select_for_update()
>   File "/home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
>     raise self.model.DoesNotExist(
> django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist.
> 
>   warn(RuntimeWarning(
> 
> [2020-11-23 17:33:19,008: WARNING/ForkPoolWorker-1] /home/ubuntu/venvs/earthalytics-api/lib/python3.8/site-packages/urllib3/connectionpool.py:981: InsecureRequestWarning: Unverified HTTPS request is being made to host 'webhook.site'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   warnings.warn(
>

**Comment by auvipy** [comment]
jango/db/models/query.py", line 429, in get
raise self.model.DoesNotExist(
django_celery_results.models.ChordCounter.DoesNotExist: ChordCounter matching query does not exist

checking this I want to know if this model present in your local DB? did you run the migrate command of django?

**Comment by auvipy** [comment]
closing as it doesn't seem to be an issue with this package. prove me wrong, please
