### ISSUE TITLE
how can I get the status for pending not only started and succeed in mysql

### ISSUE THREAD

**Issue by Guanyan1996** [celery/django-celery-results#180]
when i use CELERY_TASK_TRACK_STARTED = True

mysql saved only started or succeed not pending status

how can I config to save the pending status in mysql when i use the django-celery-results?

thx.
```
broker_url = "amqp://"
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_IGNORE_RESULT = False
CELERY_RESULT_BACKEND = 'django-db'
CELERY_TASK_TRACK_STARTED = True
enable_utc = True
CELERY_WORKER_CONCURRENCY = 1
CELERYD_PREFETCH_MULTIPLIER = 100
CELERYD_FORCE_EXECV = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10
CELERY_DISABLE_RATE_LIMITS = True

CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = "Asia/Shanghai"
DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler
```

**Comment by AllexVeldman** [comment]
Hi @Guanyan1996, Celery does not store its state when queued, [it is assumed `PENDING` if you know the TaskID.](https://docs.celeryproject.org/en/stable/reference/celery.states.html)

So to get the state in another part of your application, you could rebuild the AsyncResult using the taskID:
```python
from celery.result import AsyncResult

task = some_task.delay()
...
assert task.state == AsyncResult(task.id).state
```

**Comment by Guanyan1996** [comment]
thx.i will try it



-------- 原始邮件 --------
发件人： Allex ***@***.***>
日期： 2021年4月16日周五 晚上8:27
收件人： celery/django-celery-results ***@***.***>
抄送： yguan ***@***.***>, Mention ***@***.***>
主 题： Re: [celery/django-celery-results] how can I get the status for pending not only started and succeed in mysql (#180)

Hi @Guanyan1996<https://github.com/Guanyan1996>, Celery does not store its state when queued, it is assumed PENDING if you know the TaskID.<https://docs.celeryproject.org/en/stable/reference/celery.states.html>

So to get the state in another part of your application, you could rebuild the AsyncResult using the taskID:

from celery.result import AsyncResult

task = some_task.delay()
...
assert task.state == AsyncResult(task.id).state

―

**Comment by scholtalbers** [comment]
What would be the most straightforward way to also keep track of pending tasks in the django-celery-results table or in an companion table/model?

**Comment by AllexVeldman** [comment]
@scholtalbers I haven't tried this but I think you can do something like:
```python
@app.task(name="my-awesome-task")
def awesome_task():
     print("I do awesome stuff")

async_task = awesome_task.delay()
awesome_task.update_state(task_id=async_task.id, state="QUEUED")
```

This would call the `store_result()` on the result backend which would create a row in the TaskResult table with the state "QUEUED".

https://docs.celeryproject.org/en/stable/userguide/tasks.html#custom-states
