### ISSUE TITLE
Task Results missing sub object data

### ISSUE THREAD

**Issue by justmobilize** [celery/django-celery-results#191]
I've updated from:
- `celery==4.0.2` => `5.0.5`
- `django-celery-results==1.0.4` => `2.0.1`

My `task_results` used to have all the data, but now I get things like:
```
"(
{
  'id': '2a967b51-8996-421f-aa33-844bbfe4a581',
  'timestamp': '2021-03-19T00:15:07.550Z',
  '_links': {
    'self': {...},
    'account': {...},
    'resource': {...},
    'customer': {...}
  },
  'created': '2021-03-19T00:15:07.550Z'
}
,)"
```
What happened to the sub object data?

**Comment by justmobilize** [comment]
Doing some debugging, it appears to be this change: https://github.com/celery/django-celery-results/commit/9f89b2c7f995c59c24506e564159adf7abbfca73

Which is titled: `Add support for hiding sensitive information with celery argsrepr and kwargsrepr`

Can we make this optional?

**Comment by js-moreno** [comment]
Hi @justmobilize , any solution? I had same problem to a mail sending task

**Comment by justmobilize** [comment]
Hey @js-moreno I did. As it turns out, somewhere in the changes (not sure if in here or Celery it self), the task protocol changed to default to `2`, which somewhere is calling `celery.utils.saferepr.saferepr` which by default uses `maxlevels=3`

I'm using django, and set `CELERY_TASK_PROTOCOL = 1` in my settings and it works great
