### ISSUE TITLE
Select specific database as celery result backend

### ISSUE THREAD

**Issue by shawnngtq** [celery/django-celery-results#196]
I was wondering if there is a way to select specific database as celery result backend?

If I have 2 postgresql databases:

- `default`
- `task_db`

Based on what I observed, `django_celery_*` tables are created in `default` database. Is it possible to use `task_db`?

I find `django_celery_*` tables result clear than `celery_taskmeta` created if I use SQLAlchemy method.

I think https://github.com/celery/django-celery-results/issues/10 is somewhat related. Since I don't find much info on the doc, checking it here.

**Comment by auvipy** [comment]
why do you use two db, as par django it should be possible to point django_celery_* tables to the 2nd db as far i know, did you check django docs?

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-results/issues/10#issuecomment-273327928

**Comment by shawnngtq** [comment]
@auvipy , using 2 db because I want to separate celery task from my default db. 

In Django it's possible to point tables to 2nd db if you add db router and state the model's meta `app_label`. But since `django_celery_*` are automatically created, and I can't update the Meta, it will be created in `default` database

**Comment by auvipy** [comment]
> In Django it's possible to point tables to 2nd db if you add db router and state the model's meta `app_label`. But since `django_celery_*` are automatically created, and I can't update the Meta, it will be created in `default` database

you  can change the code in the package in your project and send PR upstream as well

**Comment by shawnngtq** [comment]
@auvipy , it sounds embarrassing, but I have no idea how to change the package code 😅 , do you have any good material on how to update django reusable app code? I suppose this is a reusable app.

**Comment by AllexVeldman** [comment]
@shawnngtq check out the database routers in Django https://docs.djangoproject.com/en/3.2/topics/db/multi-db/#topics-db-multi-db-routing
I don't have any experience with multiple databases but I think you can route all django_celery_results requests to your alternate database.

**Comment by AllexVeldman** [comment]
hi @shawnngtq, I tried separating the tasks db from the default db using Django's routers as you described:
(https://docs.djangoproject.com/en/3.2/topics/db/multi-db/)
```python
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": ENV("POSTGRES_DB"),
        "USER": ENV("POSTGRES_USER"),
        "PASSWORD": ENV("POSTGRES_PASSWORD"),
        "HOST": ENV("POSTGRES_HOST"),
    },
    "tasks_db": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "tasks_db",
        "USER": ENV("POSTGRES_USER"),
        "PASSWORD": ENV("POSTGRES_PASSWORD"),
        "HOST": ENV("POSTGRES_HOST"),
    }
}

class TasksRouter:
    route_app_labels = {'django_celery_results'}

    @staticmethod
    def db_for_read(model, **hints):
        if model._meta.app_label in TasksRouter.route_app_labels:
            return 'tasks_db'
        return None

    @staticmethod
    def db_for_write(model, **hints):
        if model._meta.app_label in TasksRouter.route_app_labels:
            return 'tasks_db'
        return None

    @staticmethod
    def allow_migrate(db, app_label, model_name=None, **hints):
        if app_label in TasksRouter.route_app_labels:
            if db == "tasks_db":
                return True
            return False
        return None


DATABASE_ROUTERS = [TasksRouter]
```

This works as expected.
There is a funny thing with the output of the migrations as they will list, even if the `allow_migrate()` returned `False`.

Also you'll have to manually create the `"tasks_db"` database in the database backend you're using and run the migrations specifically against that database `manage.py migrate django_celery_results --database tasks_db`.
With tweaking the `allow_migrate` you'll also be able to prevent other apps to be migrated to this db, then you can omit the `django_celery_results` in the `migrate`.

Inspecting the db showed me the models were created in the correct database.

Hope this helps!

**Comment by shawnngtq** [comment]
@AllexVeldman , thanks for your input!

I previously thought of adding the `app_label` of `django_celery_results`, but I don't see it in the [models](https://github.com/celery/django-celery-results/blob/master/django_celery_results/models.py) and thought it's not possible.

This is very dense info, need to try it out to understand 👍

**Comment by AllexVeldman** [comment]
@shawnngtq If this solved your problem, could you close the Issue?
