### ISSUE TITLE
task results  not support  Chinese ？

### ISSUE THREAD

**Issue by Z-Yishion** [celery/django-celery-results#197]
as follows：

@app.task
def my_task1(a=0):
    print("任务111111开始执行....")
    return "这是1"

return unicode result：

"\u8fd9\u662f1"

How to get native results？

**Comment by AllexVeldman** [comment]
@Z-Yishion If your result is a bytes object:
```python
>>> r = b"\u8fd9\u662f1"
>>> r.decode('unicode-escape')
'这是1'
```
