### ISSUE TITLE
task_ignore_result doesn't work

### ISSUE THREAD

**Issue by Bahadik** [celery/django-celery-results#203]
I don't want to store anything in my db, that's why I set `task_ignore_result = True` in my celery config. But the results are still written in `Task results` table. How can I disable writing records in this table, or at least set some expire time, so that the expired records in `Task results` table will be deleted automatically?
https://docs.celeryproject.org/en/stable/userguide/configuration.html#std-setting-task_ignore_result

**Comment by thedrow** [comment]
Please upgrade to 5.1 since we fixed this.
