### ISSUE TITLE
2.1.0 migration on Oracle

### ISSUE THREAD

**Issue by erkib** [celery/django-celery-results#208]
This migration `
migrations.AddIndex(            model_name='chordcounter',            index=models.Index(                fields=['group_id'],                name='django_cele_group_i_299b0d_idx'),        ),` produces an error when database is Oracle.

query = 'CREATE INDEX "DJANGO_CELE_GROUP_I_299B0D_IDX" ON "DJANGO_CELERY_RESULTS_CHOR1EB4" ("GROUP_ID")'
cx_Oracle.DatabaseError: ORA-01408: such column list already indexed

**Comment by auvipy** [comment]
I am not oracle expert, can you try to find a solution? we might need to adjust  index codes

**Comment by AllexVeldman** [comment]
I think this might have to do with `ChordCounter.unique = True` and #161 moving the `db_index=True` to the `Meta.indexes` probably causing 2 indexes to be created.

**Comment by AllexVeldman** [comment]
@erkib I confirmed on Postgres that 2 indexes are created, 1 unique and 1 regular. I i make a PR, would you be able to check the migration on Oracle?

**Comment by erkib** [comment]
> @erkib I confirmed on Postgres that 2 indexes are created, 1 unique and 1 regular. If i make a PR, would you be able to check the migration on Oracle?

Unfortunately Oracle still doesn't like it:
2021-06-29 08:27:52,529  DEBUG    CREATE INDEX "DJANGO_CELE_GROUP_I_299B0D_IDX" ON "DJANGO_CELERY_RESULTS_CHOR1EB4" ("GROUP_ID"); (params None)
2021-06-29 08:27:52,555  DEBUG    (0.026) CREATE INDEX "DJANGO_CELE_GROUP_I_299B0D_IDX" ON "DJANGO_CELERY_RESULTS_CHOR1EB4" ("GROUP_ID"); args=None
cx_Oracle.DatabaseError: ORA-01408: such column list already indexed

It 's because of the 0009 migration is faulty and the migration tool never gets to your (0010) migration. When I locally removed 0009 and yours and ran the makemigrations with the changes in models.py of yours, it generated a migration that was successful on oracle.

**Comment by AllexVeldman** [comment]
@erkib So the fix is a bit more complicated, could you try the current state of the PR?
and if it works could you also try to revert back to migration 0008 to make sure we don't break backing out on Oracle?

**Comment by erkib** [comment]
> @erkib So the fix is a bit more complicated, could you try the current state of the PR?
> and if it works could you also try to revert back to migration 0008 to make sure we don't break backing out on Oracle?

This time migration 0009 was successful, but 0010 gave an error that those indexes do not exist:
Applying django_celery_results.0010_remove_duplicate_indices...2021-07-01 06:07:05,927  DEBUG    DROP INDEX "DJANGO_CELE_GROUP_I_299B0D_IDX"; (params ())
2021-07-01 06:07:05,931  DEBUG    (0.004) DROP INDEX "DJANGO_CELE_GROUP_I_299B0D_IDX"; args=()
cx_Oracle.DatabaseError: ORA-01418: specified index does not exist
As long as you fake adding them in 0009, 0010 won't be able to drop them unless you have already migrated to 0009 on other database engines. Using Oracle backend this path is not working because old 0009 didn't succeed.

**Comment by AllexVeldman** [comment]
@erkib thank you! on Postgres it did not raise any exceptions dropping non-existing indexes so i was not able to see what would be raised. will add the catch.

**Comment by AllexVeldman** [comment]
@erkib sorry for asking you to test so often, the current state of the PR includes the catch. could you try again?

**Comment by erkib** [comment]
no problem at all, I'm also interested in moving forward with this upgrade :)
I can confirm now that these migrations also work on Oracle. Good job!
For future reference if somebody is interested in also testing with Oracle locally - there's a free Docker image available in Hub, all you have to have is a Docker account and you have to subscribe to the Oracle images. Search for 'Oracle Database Enterprise Edition'.

**Comment by AllexVeldman** [comment]
Good to hear. 

I wrongly assumed the enterprise version needed a licence, will see if I can get that to work when I'm working on this project again.

**Comment by intgr** [comment]
With version 2.2.0, if I run `makemigrations` in my project, Django now thinks there are unmigrated changes in django_celery_results. And it actually creates a new migration file under the `site-packages` directory. :(

However, if I run `makemigrations` in django-celery-results project, no migration changes are detected. I'm not yet sure how my project differs. I will update if I figure it out.

```
% ./manage.py makemigrations 
Migrations for 'django_celery_results':
  /.../python3.9/site-packages/django_celery_results/migrations/0011_auto_20210719_0953.py
    - Remove index django_cele_date_cr_bd6c1d_idx from groupresult
    - Remove index django_cele_date_do_caae0e_idx from groupresult
    - Remove index django_cele_task_na_08aec9_idx from taskresult
    - Remove index django_cele_status_9b6201_idx from taskresult
    - Remove index django_cele_worker_d54dd8_idx from taskresult
    - Remove index django_cele_date_cr_f04a50_idx from taskresult
    - Remove index django_cele_date_do_f59aad_idx from taskresult
    - Create index django_cele_date_cr_0d69cb_idx on field(s) date_created of model groupresult
    - Create index django_cele_date_do_030540_idx on field(s) date_done of model groupresult
    - Create index django_cele_task_na_4bcd60_idx on field(s) task_name of model taskresult
    - Create index django_cele_status_9c2623_idx on field(s) status of model taskresult
    - Create index django_cele_worker_d87a3d_idx on field(s) worker of model taskresult
    - Create index django_cele_date_cr_2b7193_idx on field(s) date_created of model taskresult
    - Create index django_cele_date_do_c4aa5e_idx on field(s) date_done of model taskresult
```

**Comment by intgr** [comment]
The issue I described above also occurs in 2.1.0, so it's unrelated to this bug or the fix. I reported a new issue #222.
