### ISSUE TITLE
Inconsistent urls naming pattern

### ISSUE THREAD

**Issue by insspb** [celery/django-celery-results#213]
Before group results was added it was clear why there was no separation for task/group.

But now things become terrible, as tasks has no postfix, and groups has.

My proposal is completely change url schema of the app:
Make it this classic way:

Instead of `<task_pattern:group_id>/group/done/` make `group/done/<task_pattern:group_id>/`
instead of `<task_pattern:task_id>/done/` make `task/done/<task_pattern:task_id>/`

Etc for other 2 existed links. It will make possible to extend schema with task/group lists and filters without url mess. 
Like: `task/done/` with list of all done tasks. 

Such links can be added to this app directly in future, or at least developers will have an opportunity to do it themself in easy way.

**Comment by auvipy** [comment]
@AlecTroemel

**Comment by AlecTroemel** [comment]
I think the suggestion is good. @auvipy what are your thoughts on a "breaking" change like this? Would you want to see both URL schema's exist at the same time for a while to announce the deprecation of the old one?

**Comment by auvipy** [comment]
>  Would you want to see both URL schema's exist at the same time for a while to announce the deprecation of the old one?

I would prefer so
