### ISSUE TITLE
default_app_config Warning

### ISSUE THREAD

**Issue by Niccolum** [celery/django-celery-results#220]
RemovedInDjango41Warning: 'django_celery_results' defines default_app_config = 'django_celery_results.apps.CeleryResultConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

Can you do something like in your subproject?
https://github.com/celery/django-celery-beat/issues/408

**Comment by auvipy** [comment]
yes https://github.com/celery/django-celery-beat/blob/master/django_celery_beat/__init__.py#L34

**Comment by Niccolum** [comment]
@auvipy can you add this changes to django_celery_results?

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-results/pull/221 done
