### ISSUE TITLE
django 4.0 support

### ISSUE THREAD

**Issue by auvipy** [celery/django-celery-results#259]

**Comment by rh0dium** [comment]
- [ ] remove `default_app_config`
- [ ] `setup.py` updates

If you need help holler!

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-results/blob/master/django_celery_results/__init__.py#L34 is not needed. setup & CI entry needed probably

**Comment by auvipy** [comment]
also keep in mind that django 4.0 has some regressions which are fixed in main branch & waiting a bug fix release very soon
https://github.com/celery/django-celery-results/pull/272
