### ISSUE TITLE
Celery app fails when importing Django user model

### ISSUE THREAD

**Issue by Six-wars** [celery/django-celery-results#26]
![screenshot from 2017-09-12 21-07-18](https://user-images.githubusercontent.com/15666437/30342181-90635476-9801-11e7-937f-5b15bce3c9b7.png)

as in snapshot and highlighted text in red I have this line 

`from gallery.colorfest import render_full`

which inside goes to import Django user model and it fails claiming apps not installed. If I un comment this line it works, so with possibly a good amount of code reshuffling I might get it to work but I believe figuring this out will end up making a more streamlined implementation.

**Comment by auvipy** [comment]
can you show your real codes?

**Comment by Six-wars** [comment]
resolved it a while back
