### ISSUE TITLE
default task celery.backend_cleanup triggered repeatedly very much

### ISSUE THREAD

**Issue by heng-zhang-20** [celery/django-celery-results#275]
# Environment

- celery==5.2.1
- Django==3.2.9
- django-celery-beat==2.2.1
- django-celery-results==2.2.0
- redis==4.0.2

# Config

```
# celery.py
from celery import Celery
from . import celeryconfig
from django.utils import timezone

app = Celery('xxx Celery') 
app.config_from_object(celeryconfig)
app.autodiscover_tasks()
app.now = timezone.now
app.loader.override_backends['django-db'] = 'django_celery_results.xxx.database:DatabaseBackend'

# celeryconfig.py
import os
from django.conf import settings
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "xxx.settings")
broker_url = 'redis://xxx:6379/8'
result_backend = 'django-db'
worker_concurrency = 2
worker_prefetch_multiplier = 5
worker_max_tasks_per_child = 100
enable_utc = False
timezone = settings.TIME_ZONE
```

# Table record

## crontabschedule record
![image](https://user-images.githubusercontent.com/67679070/147319655-5f650774-6af8-47fa-b775-5d66c31a530c.png)
## task record
![image](https://user-images.githubusercontent.com/67679070/147319790-84f0e42a-c157-4ffa-bc9d-5a07d4223269.png)

# Description

There are too many records in django_celery_results_taskresult table about  default task celery.backend_cleanup.

`SELECT id,status,task_name,date_created,date_done FROM django_celery_results_taskresult where date_created > "2021-12-23 20:00:000.000000" and task_name="celery.backend_cleanup" LIMIT 100;`

As you can see, that task was triggered dozens of times in 1 second.

**Does it make sense?**

![image](https://user-images.githubusercontent.com/67679070/147319177-d5fb02d6-182c-430e-94b8-2a9fcb4a144d.png)

**Comment by auvipy** [comment]
thanks for your report, we have a planned new release for this package and its sister one, in the meantime if you can check if anything from https://github.com/celery/django-celery-results/compare/v2.2.0...master commit log solves your issue. if not we will look for solution for sure.

**Comment by heng-zhang-20** [comment]
I didn't find something useful for solving this issue.  Does anyone else report issue like this?

Besides, why dose this task run during 20:00 to 23:59 while it was defineded running at 04:00?

**Comment by heng-zhang-20** [comment]
Once I start Celery process, it will receive too many celery.backend_cleanup tasks even if task is not enabled. It looks like an endless loop, and process use lots of cpu. And there are too many values in Redis celery key.

![image](https://user-images.githubusercontent.com/67679070/147436230-cdc41671-f912-4cd5-a380-223e2f446b6e.png)

![image](https://user-images.githubusercontent.com/67679070/147436351-b6ba4b58-80cc-43db-a7be-8e4085b75ce5.png)

**Comment by heng-zhang-20** [comment]
From 2021-12-27 20:00:00 to 2021-12-28 08:45:21, celery.backend_cleanup ran 3,136,805 times.

![image](https://user-images.githubusercontent.com/67679070/147520198-79b37fc2-5549-4b48-a8d4-154d8d886d20.png)

![image](https://user-images.githubusercontent.com/67679070/147520218-ef5e72ff-c21f-455c-aaf8-63fdd1273377.png)

**Comment by auvipy** [comment]
will come to this after completing pending release tasks

**Comment by heng-zhang-20** [comment]
I set Django settings USE_TZ = True and set Celery config enable_utc = True, the problem goes away. It looks like a problem about time zone and utc settings.

**Comment by auvipy** [comment]
thanks for claryfying
