### ISSUE TITLE
ReadTheDocs site extremely out of date

### ISSUE THREAD

**Issue by matthewarmand** [celery/django-celery-results#279]
On both the [README](https://github.com/celery/django-celery-results#celery-result-backends-using-the-django-ormcache-framework) and on [PyPI](https://pypi.org/project/django-celery-results/), users are pointed to <https://django-celery-results.readthedocs.io> for documentation on this library. The `latest` version according to the [ReadTheDocs site](https://django-celery-results.readthedocs.io/en/latest/) and [Change History](https://django-celery-results.readthedocs.io/en/latest/changelog.html) is `1.1.2`, released 2019-06-06. In fact, on the main site there's even a discrepancy:

![image](https://user-images.githubusercontent.com/4631191/148239315-8e07f7d0-a5bc-4b97-b433-2501fa2a7605.png)

There are 6 version tags on this repo newer than `1.1.2`, but they're not reflected in ReadTheDocs at all. Is this a problem with the release process where the docs should be updating but are not? Or is there some new way of documenting the library and its changelog and ReadTheDocs is being retired? Obviously the official documentation being this out of date is a problem for anyone who isn't for some reason stuck on version `1.1.2`.

**Comment by auvipy** [comment]
ops! thanks for the report! have to check what went wrong!

**Comment by matthewarmand** [comment]
Fwiw the discrepancy on the RTD site seems to be due to the fact that the version on the README was out of date for version `1.1.2` (See [here](https://github.com/celery/django-celery-results/tree/1.1.2#celery-result-backends-using-the-django-ormcache-framework)). Looks like sometime between `1.1.2` and `1.2.0` whatever mechanism updates the docs site was broken.
