### ISSUE TITLE
New release with Django 3.2 support

### ISSUE THREAD

**Issue by arghodayah** [celery/django-celery-results#282]

**Comment by auvipy** [comment]
i think django 3.2 supported version is already released, django 4.0 support is also done in development branch just a release is due

**Comment by arghodayah** [comment]
does 2.2.0 supports Django 3.2? it's not mentioned in [pypi.org](https://pypi.org/project/django-celery-results/2.2.0/)

**Comment by auvipy** [comment]
the trove classifier was not updated sadly, but 3.2 is supported

**Comment by auvipy** [comment]
https://pypi.org/project/django-celery-results/2.3.0/
