### ISSUE TITLE
error on upgrades: relation "django_celery_results_taskresult" does not exist

### ISSUE THREAD

**Issue by kgeographer** [celery/django-celery-results#284]
I know there is a closed issue on this message, but that discussion doesn't help me. Now upgrading an app, on MacOs (intel) 
- Python 3.7.4 to 3.10.2
- Django 2.2 to 3.2
- Celery 4.4.7 to 5.2.3
- django-celery-results 1.0.2 to 2.2.0

With the old versions, things worked, i.e. writing task results to a `celery_results_taskresults` table, reading from it to filter querysets, etc. Went through the [code changes documented on the Celery site](https://docs.celeryproject.org/en/stable/internals/deprecation.html). For me this meant changing `from celery.decorators import task` to `from celery import shared_task`, then changing view decorators from `@task` to `@shared_task`.

I now get this error, not when running a task, but when navigating to pages that display querysets that have been filtered by values in `celery_results_taskresult`. Simplest way to reproduce it is in a python console:

```
from django_celery_results.models import TaskResult
TaskResult.objects.all()

```
result is -> "django.db.utils.ProgrammingError: relation "django_celery_results_taskresult" does not exist
LINE 1: ...", "django_celery_results_taskresult"."meta" FROM "django_ce..."

I see it's expecting a different name than the table I have, so I tried renaming my table, adding the 'django_' to `celery_results_taskresult`, but get the same error. I remember now having to change this table name 4 years ago when I first implemented Celery and django-celery-results (removed the 'django_' at the start) and never understood why.

This package has worked perfectly (thanks, btw) and my app is highly dependent on it - any ideas?

**Comment by auvipy** [comment]
after upgrading did you run migrate command? as the new release include newer schema migrations
