### ISSUE TITLE
MySQL error on migrate persists

### ISSUE THREAD

**Issue by benselme** [celery/django-celery-results#285]
I'm aware of `DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH`.

However migration `0004_auto_20190516_0412.py` still fails with `django.db.utils.OperationalError: (1709, 'Index column size too large. The maximum column size is 767 bytes.')` because it's trying to create the `task_name` column which is 255-characters long and indexed.

**Comment by auvipy** [comment]
can you elaborate more on the versions of everything you are using?

**Comment by benselme** [comment]
The database is MariaDB 10.1.48, but I deploy on an older version, 5.5.60

**Comment by benselme** [comment]
That would be MySQL 5.6 which is equivalent to MariaDB 10.1. For MariaDB >= 10.2.2, the server setting `innodb_large_prefix` defaults to `ON`, which should remove the limitation that causes the crash.

**Comment by auvipy** [comment]
> but I deploy on an older version, 5.5.60

sorry can't accept any contribution for unsuported versions :)

**Comment by benselme** [comment]
You misread what I wrote. Django 2.2 supports MySQL 5.6 and so also MariaDB 10.1, on which the problem happens.
