### ISSUE TITLE
NotImplementedError: No result backend is configured.

### ISSUE THREAD

**Issue by Argonautic** [celery/django-celery-results#29]
I'm using django, postgres, ubuntu, and (obviously) celery + django-celery-results. I'm following the django guide on the official celery docs that links to this package. In my app's settings.py, CELERY_RESULT_BACKEND is set to 'django-db', and when I check my postgres database, I do see a table for public.django_celery_results_taskresult correctly populating with results, but when I try to access them from a python shell in the following manner:

```
from tasks import add
result = add.delay(5, 5) 
result.get()
```

I get the error "NotImplementedError: No result backend is configured."

For the life of me, I can neither figure out why this is happening nor find any answers online.

My celery.py file is:
```

from __future__ import absolute_import, unicode_literals
import os
from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'BeerAggregate.settings')

app = Celery('BeerAggregate')

app.config_from_object('django.conf:settings', namespace='CELERY')

app.autodiscover_tasks()

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

Finally, when I access the celery shell through

`celery -A BeerAggregate -l info`

 The config message looks like this:

```
[config]
.> app:         BeerAggregate:0x7f5f0e4159e8
.> transport:   amqp://guest:**@localhost:5672//
.> results:     
.> concurrency: 4 (prefork)
.> task events: OFF (enable -E to monitor tasks in this worker)
```

The results section is empty

**Comment by wardal** [comment]
Just to be sure, did you import tasks from app with tasks.py and def "add"?

I'm tried to check your problem, I had almost the same env: django 1.11+ubuntu14.04+celery 4.1.0+django-celery-results (I'm also have django-celery-beat, but I did not started beat worker for this experiment). Also as message broker I used redis, not amqp. Generally, all worked fine:

```
 -------------- celery@vagrant-ubuntu-trusty-64 v4.1.0 (latentcall)
---- **** ----- 
--- * ***  * -- Linux-3.13.0-133-generic-x86_64-with-Ubuntu-14.04-trusty 2017-10-20 10:52:33
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         Application:0x7f0806438ef0
- ** ---------- .> transport:   redis://127.0.0.1:6379//
- ** ---------- .> results:     
- *** --- * --- .> concurrency: 2 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

```

```
from myapp.tasks import add
result = add.delay(5, 5)
result.get()
10
```

```
[2017-10-20 10:52:33,476: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2017-10-20 10:52:33,483: INFO/MainProcess] mingle: searching for neighbors
[2017-10-20 10:52:34,504: INFO/MainProcess] mingle: all alone
[2017-10-20 10:52:34,528: INFO/MainProcess] celery@vagrant-ubuntu-trusty-64 ready.
[2017-10-20 10:53:27,859: INFO/MainProcess] Received task: myapp.tasks.add[22305642-ee06-437b-9a74-cf6c06176954]  
[2017-10-20 10:53:27,952: INFO/ForkPoolWorker-1] Task myapp.tasks.add[22305642-ee06-437b-9a74-cf6c06176954] succeeded in 0.09163595999962126s: 10
```

settings.py:
```
# Configuration for Celery
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
```

**Comment by Argonautic** [comment]
Hi wardal -thanks for the quick response! I was indeed importing tasks correctly, but the way you phrased your question lead me to investigate something else which turned out to be the problem: I was running `python` straight instead of using `python manage.py shell` from the base directory, and upon using `python manage.py shell` I easily accessed my results.

So this wasn't a fault of django-delery-results at all, but I would call it a gap in documentation in the official celery docs. Thank you for the help!
