### ISSUE TITLE
Intentional that psycopg2 is an unconditional import?

### ISSUE THREAD

**Issue by cayla** [celery/django-celery-results#293]
Hi, 

I just picked up 2.3.0 and immediately had some issues.  Celery is failing with `ModuleNotFoundError: No module named 'psycopg2'` and it looks like that comes from yesterday's https://github.com/celery/django-celery-results/commit/28fb1c64fd44684d16b69d15083a01cb9047d3d8

As much as I would prefer to be using Postgres, I am stuck with mariaDB on a project.  :) 

Thanks,

**Comment by auvipy** [comment]
https://github.com/celery/django-celery-results/pull/292 to get rid of it & we are going to switch to psycopg2-binary

**Comment by violuke** [comment]
@auvipy can a release please be made on PyPI? Currently, this is a breaking change from 2.2.0 to 2.3.0 which it shouldn't be for SemVer. Thanks for your help.
