### ISSUE TITLE
Error in: Applying django_celery_results.0007_remove_taskresult_hidden...

### ISSUE THREAD

**Issue by mascDriver** [celery/django-celery-results#295]
When run migrate of the app, happend error in firebird during the migrate 0007:
```fdb.fbcore.DatabaseError: ("Error while executing SQL statement:\n- SQLCODE: -607\n- unsuccessful metadata update\n- ALTER TABLE DJANGO_CELERY_RESULTS_TASKR5A9B failed\n- no current record for fetch operation\n- At trigger 'RDB$TRIGGER_23'", -607, 335544351)```
I have tried in 2 computers and receive the same error, only firebird.

**Comment by auvipy** [comment]
i don't think we support firebird DB back end yet
