### ISSUE TITLE
`error in index django_celery_results_taskresult_hidden_cd77412f` on Django 4.1

### ISSUE THREAD

**Issue by orf** [celery/django-celery-results#340]
On Django 4.1 running `migrate` on an empty, fresh sqlite database errors with:

```
django.db.utils.OperationalError: error in index django_celery_results_taskresult_hidden_cd77412f after drop column: no such column: hidden
```

This is fixed in Django 4.1.1 (ticket: https://code.djangoproject.com/ticket/33899). Until then users need to downgrade to 4.0.6.

This is partly an FYI for others, because I couldn't find much info on this issue.

**Comment by mirekdlugosz** [comment]
Django 4.1.1 [has been released yesterday](https://www.djangoproject.com/weblog/2022/sep/05/bugfix-release/).

On my project, I no longer encounter above error when running on Django 4.1.
