### ISSUE TITLE
Periodic Task Name missing from admin detail (only shows in list view)

### ISSUE THREAD

**Issue by peterfarrell** [celery/django-celery-results#342]
The new `periodic_task_name` added in #261 was added to only the list display and list filter in the Django admin list view.  The periodic task name is missing from the `fieldsets` configuration.

**Comment by peterfarrell** [comment]
See PR #343 to fix the parity issue between the list and detail views.

**Comment by peterfarrell** [comment]
PR was merged so this issues should have been closed.

**Comment by auvipy** [comment]
thank you
