### ISSUE TITLE
how to decode results field in postgress?

### ISSUE THREAD

**Issue by stanhjr** [celery/django-celery-results#344]
I want to be able to see the results of tasks in postgress, but there is some strange format, I can't decode it.

Please tell me the solution to this problem

here is my celery config

`task_serializer    = 'json'
task_compression   = 'gzip'
accept_content = ['json', ]

result_serializer  = 'json'
result_expires     = 7200,
result_compression = 'gzip'

event_serializer = 'json'

redis_max_connections = 2

broker_pool_limit        = 2
broker_transport_options = {
    'max_connections': 2
}

task_ignore_result = True
task_store_errors_even_if_ignored = True
database_table_schemas = {
        'task': 'celery_tables',
        'group': 'celery_tables',
}
result_extended = True`

this is datatype in postgres (result field)
` \x80059593000000000000007d94288c086578635f74797065948c14546f6f4d616e7952657175657374734572726f72948c0b6578635f6d657373616765948c26546f6f206d616e792072657175657374732c20706c65617365207265747279206c617465722e9485948c0a6578635f6d6f64756c65948c237372632e636f6d6d6f6e2e636f6d6d756e69636174696f6e2e6170695f636c69656e7494752e
`

**Comment by auvipy** [comment]
you can try flower

**Comment by richard-scott** [comment]
@auvipy 
> you can try flower

How do you configure Flower to use the Django-DB, what URL does it need?
