### ISSUE TITLE
Issue installing master via poetry

### ISSUE THREAD

**Issue by orf** [celery/django-celery-results#360]
If you install this project with Poetry, you get the following error:

```
        error in django_celery_results setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
            pytz>dev
```

I believe we can just get rid of the `>dev` specifier?

**Comment by amo13** [comment]
Landed here following an installation issue with the [AUR package](https://aur.archlinux.org/packages/python-django-celery-results). Could we please have a new minor release including this fix? Then I'd ask the package maintainer to update it so it installs/updates without manual intervention on archlinux.
Thanks!

**Comment by auvipy** [comment]
yeah we should release a new version ASAP

**Comment by amo13** [comment]
Hey, can we please have a new minor release including this fix?
