### ISSUE TITLE
Job Names

### ISSUE THREAD

**Issue by ACPK** [celery/django-celery-results#38]
How do I see the name on the job?

**Comment by sobolevn** [comment]
Indeed, how is that possible?

I have seen several pull-requests to implement this feature, but none of them are merged.
https://github.com/celery/django-celery-results/pull/34
https://github.com/celery/django-celery-results/pull/14

Do you guys need any help implementing this feature?

**Comment by ACPK** [comment]
@sobolevn - I haven't tested it yet, but it seems that the feature was recently merged in:

https://github.com/celery/django-celery-results/pull/14

**Comment by sobolevn** [comment]
I am using http://django-celery-monitor.readthedocs.io/en/latest/ it solves all issues this package has:
1. Clean admin UI
2. Full tasks information
3. Expiration times
