### ISSUE TITLE
TaskResult doesn't send Django post_save signals

### ISSUE THREAD

**Issue by keeper** [celery/django-celery-results#41]
I'm trying to do something when a task being written to database or its status updates with code like this:
```
from django.db.models.signals import post_save
from django_celery_results.models import TaskResult
from django.dispatch import receiver

@receiver(post_save, sender=TaskResult, dispatch_uid='task_update') 
def task_update(sender, instance, created, **kwargs):
    # do something
```

But nothing happened. Did I miss something, or I should use celery.signals?

I'm using rabbit-mq, and some packages' versions are following:
```
Django (1.11.4)
django-celery-results (1.0.1)
celery (4.1.0)
```

**Comment by atkawa7** [comment]
@keeper I had a similar issue with this one. Mine was related to django autocommit mode. See [django docs](https://docs.djangoproject.com/en/2.1/topics/db/transactions/#why-django-uses-autocommit).

```python
from django.db import transaction

def some_celery_task(arg1):
        pass
@receiver(post_save, sender=TaskResult)
def update_reports(sender, instance=None, created=None, **kwargs):
    if  created:
           transaction.on_commit(lambda:  some_celery_task.delay('arg1'))
```

**Comment by auvipy** [comment]
What's the update on this issue?

**Comment by keeper** [comment]
I've left the project and haven't work on this for awhile. However I think this issue was solved and was due to a misconfiguration, I'll close this issue.
