### ISSUE TITLE
Latest release number is behind current master

### ISSUE THREAD

**Issue by thclark** [celery/django-celery-results#47]
Hi all, some substantial changes have been made in the last 15 months, including the database migration to 0002 in the recent merge #34 .

Is there any chance of a new release (to 1.0.2??) to correspond with this, please? It'd help with tracking migrations and dependencies when `pip install`ing a version, rather than setting a specific commit SHA :)

Thanks!

**Comment by thedrow** [comment]
No it is not abandoned.
We are currently busy with releasing Celery 4.2.
