### ISSUE TITLE
Wrong application name in 0002 migration

### ISSUE THREAD

**Issue by danie1k** [celery/django-celery-results#51]
#34 introduced new migration `0002_add_task_name_args_kwargs` with following dependencies:
```
    dependencies = [
        ('celery_results', '0001_initial'),
    ]
```
but application name is `django_celery_results`, **not** `celery_results`.

That causes following issue, after installing package:
```
django.db.migrations.exceptions.NodeNotFoundError: Migration django_celery_results.0002_add_task_name_args_kwargs dependencies reference nonexistent parent node ('celery_results', '0001_initial')
```

**Comment by yangtao4389** [comment]
yes,I must use `python3 manage.py migrate celery_results ` can effective

**Comment by danie1k** [comment]
FYI: Resolved some time ago by https://github.com/celery/django-celery-results/commit/bb247561918f078837fc14f85b61c66556009eda.
