### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by xfxf** [celery/django-celery-results#61]
Hi - now that Celery 4.2 is released, is it possible to do a new release?  I've been using a Celery 4.2 pre-release for a while and had to point to a later django-celery-results commit for it to work (4cc5f274b5d59d72f243e15d2d67c02a410b8b1d); I don't recall why (it wouldn't have been due to that specific commit; that was probably just the latest at the time I did it). 

Last release was quite some time ago.

**Comment by jathanism** [comment]
Seconded. I'd really like the name/args/kwargs fields in `TaskResult`! It's been in the master branch for a while and I'm really trying to hold out on forking!

**Comment by woegjiub** [comment]
Is there any ETA on this?
We've been specifying git-master in our Pipfile for a while now and it's been working perfectly, but it would be really nice to have a release on pypi to point to instead.

**Comment by auvipy** [comment]
@thedrow

**Comment by munavvar20** [comment]
Any ETA on the new release?

**Comment by xblitz** [comment]
yes please, just a release!

**Comment by marcomayer** [comment]
Yes, it's been a while since celery 4.2 was released and just using the latest master isn't a stable solution.

**Comment by thedrow** [comment]
I'm really sorry this took so long.
1.0.2 is out :)
