### ISSUE TITLE
ProgrammingError: relation "celery_results_taskresult" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "celery_results_taskresult...

### ISSUE THREAD

**Issue by ACPK** [celery/django-celery-results#66]
When I tried out the master version (1.0.2), I receive the following error when visiting /admin/celery_results/taskresult.

    ProgrammingError: relation "celery_results_taskresult" does not exist
    LINE 1: SELECT COUNT(*) AS "__count" FROM "celery_results_taskresult...

**Comment by liquidpele** [comment]
You have to run django migrations.
