### ISSUE TITLE
Quick Question: Using the cache backend, when does the result expire?

### ISSUE THREAD

**Issue by fxfitz** [celery/django-celery-results#67]
How does expiry work when using the cache result backend?

**Comment by fxfitz** [comment]
Bump.

**Comment by liquidpele** [comment]
The cache backend is configured by you, so however you configure it, and the defaults depend on the cache backend you use. 

https://docs.djangoproject.com/en/2.2/topics/cache/

**Comment by liquidpele** [comment]
Oops, sorry, celery configures it's own cache backend.

**Comment by auvipy** [comment]
better post questions ins mailing list or IRC first.
