### ISSUE TITLE
missing migration

### ISSUE THREAD

**Issue by jaredmcdonald** [celery/django-celery-results#68]
with a fresh install (django version 2.1.2) I'm getting a migration not committed to source:

```
Migrations for 'celery_results':
  /path/to/virtualenv/lib/python3.6/site-packages/django_celery_results/migrations/0003_auto_20181004_1724.py
    - Change Meta options on taskresult
```

**Comment by auvipy** [comment]
could you check the codes and delete old migrations to generate a fresh new one which works, and send as a pr?

**Comment by jaredmcdonald** [comment]
sorry, didn't have a chance to circle back until now, but this appears to have been done: https://github.com/celery/django-celery-results/blob/master/django_celery_results/migrations/0003_auto_20181106_1101.py

closing!
