### ISSUE TITLE
Store task name ?

### ISSUE THREAD

**Issue by kedare** [celery/django-celery-results#7]
Hello.

Would there be a way to store the task name with the result ? If not, how to know what is the task associated with a result ?

Thanks.

**Comment by stuartaccent** [comment]
Hi, Have been watching this as wanted the same thing, have had a play and have got what I need by doing the following. 

[https://github.com/stuartaccent/django-celery-results/commit/09403793f0c98eb063c344e5f355e3d0ae2da8ce](url)

In all cases ive found so far the task '''foo.tasks.some_task''' is part of the request but im not sure if this is always the case, so I wont pr it. Think it needs someone to look at it with more knowledge of celery as only been using it for about 3 hours :)

Stu

**Comment by ask** [comment]
You're right, `self.request.task` contains the task name but this is not documented and merely a side effect of the message dictionary being reused to avoid a copy.

It's not going to go away though, and it's present in all transports, message protocol one and two.

**Comment by cw-andrews** [comment]
Not sure if this is still open but I too think it would be great if the task name were added as a foreign key. Additionally, in my opinion it might be a good idea to store the arguments in the results table as well (In case they change in the PeriodicTask table. 

Regardless, good work, this is definitely something I could use!

**Comment by rmad17** [comment]
This feature to store some reference or info or foreign key to some other table would be really useful. Very nice project btw.

**Comment by oortega** [comment]
@stuartaccent  please store reference foreign key with periodic task. Great Job.

**Comment by Puciek** [comment]
For those interested, I've @cw-andrews you may be interested in my branch then, it stroes task name and task arguments, with index on task name for quicker queries https://github.com/Puciek/django-celery-results

**Comment by rmad17** [comment]
For now what I did is to return a dictionary with relevant details. Task result stores that dictionary.

**Comment by cw-andrews** [comment]
Thanks for that @Puciek

**Comment by psychok7** [comment]
Would be nice if any of the open PRs would be merged

**Comment by jezdez** [comment]
I've released [django-celery-monitor](http://django-celery-monitor.readthedocs.io/), a port of the task and worker monitoring feature from django-celery to Celery 4.x. It uses Celery's event system to get status updates about tasks and workers, so contains a lot more information than the django-celery-results backend can offer.

I would encourage the authors of this app to close the ticket in favor of django-celery-monitor as I think it's better suited for the purpose of tracking task arguments etc.

**Comment by capooti** [comment]
great work! I am now trying @Puciek branch in our project. It would make sense to have it merged. Looking with interest to django-celery-monitor as well @jezdez

**Comment by guohongze** [comment]
Would there be a way to store the Periodic tasks name with the result ? @stuartaccent 's method only store the task name like demoapp.tasks.add, cannot store table 'django_celery_beat_periodictask''s name field.

**Comment by rmad17** [comment]
Great work @jezdez . I have a question before I try this. Would this offer any advantage over flower?

**Comment by jezdez** [comment]
@rmad17 No, this is specifically a solution targeted at the integration with Django's ORM and the admin system. Flower in fact offers many other features such as configuration management and graphing the current use.

**Comment by jezdez** [comment]
@rmad17 Oh, I should note, that I think Flower has issues right now with Celery 4, but that's of course only a transient problem.

**Comment by capooti** [comment]
Yes it is definitely a problem with @Puciek branch.

**Comment by Puciek** [comment]
@capooti how did you get to a spot where your tasks don't have a task ID?

**Comment by capooti** [comment]
@Puciek it looks to be an error in the logic of our code. Under some conditions the code was running update_state even when celery is not running (which is a possible configuration of our application). Sorry for the noise

**Comment by Puciek** [comment]
@capooti phew! That got me worried a bit because having the task Id is an essential part of a task, so that bit missing would be big problem! Glad that it's resolved!

**Comment by capooti** [comment]
Sorry about that. On a side note, when running that code, the task name is set to None. Maybe should I include it as a parameter in update_state? Thanks again

**Comment by keeth** [comment]
@Puciek did you just delete your fork?  i was using it :)
Guess I will try @stuartaccent's instead.

**Comment by Puciek** [comment]
Heya, @keeth I have not, it's there. What issue are you seeing?

**Comment by keeth** [comment]
@Puciek nm, i misspelled the repo -_- 

Thanks for your code, it's just what I needed.

Would be cool if one of these forks got merged.

**Comment by jjorissen52** [comment]
Could we possibly get a version with this change uploaded to PyPi?

**Comment by frontendr** [comment]
That would be awesome, installing a 'dev' version on a production environment isn't something I'd like to keep doing.

**Comment by itsanishjain** [comment]
I try to create task with this name
```
@shared_task(name = 'update__info')
def myFun():
      pass

```
and I am using `django-celery-result` for storing results but task name is showing

***

![Screenshot from 2022-07-03 00-22-26](https://user-images.githubusercontent.com/43033153/177013032-3d27f29c-a693-407b-bb2b-ebac1e881471.png)

**Comment by buoncri** [comment]
try to add settings.py

CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXTENDED = True
