### ISSUE TITLE
Request to add "date created" to TaskResult model

### ISSUE THREAD

**Issue by steresi** [celery/django-celery-results#87]
The TaskResult Model (e.g. stored in django_celery_results_taskresult) has a "date_done" field, but I recommend it should also have a "date_created". Since the record will be modified when the task is completed, the "date_done" may be different from the creation date.

A creation date would be very useful for checking when a task was submitted vs. when it was actually completed.

**Comment by auvipy** [comment]
you can come with a pr with new migrations

**Comment by ZviBaratz** [comment]
@auvipy can this be closed? Seems to be merged and working :+1:

**Comment by bigott-a** [comment]
@auvipy I might have an issue with the field `date_created`

I've created a sample to reiterate it:

task.py
```python
@shared_task(bind=True, name="default_task")
def default_task(self, files=None):
    start = str(timezone.now())
    sleep(10)
    end = str(timezone.now())
    return f"{start=}\n{end=}"
```

The task is well executed and returned:
```shell
Task default_task[0dd3e0e8-b967-4b47-a507-1924f9383534] succeeded in 10.048574910964817
s: 
start = '2022-02-16 07:28:49.910870'
end = '2022-02-16 07:28:59.931319'
'
```

But if I checked the content the table `task_result`, date_created is nearly equal to the date_done:
date_done = 2022-02-16 14:28:59.95575+01
date_created = 2022-02-16 14:28:59.9554+01

I was expecting to get the start time of task in date_created.
Is it normal ?

**Comment by auvipy** [comment]
probably it completes very fast?
