### ISSUE TITLE
celery backend mysql database record has chinese messy 

### ISSUE THREAD

**Issue by liuhetongzi** [celery/django-celery-results#89]
celery version: 4.2.1
django version: 1.9.10
django-celery-results version: 1.0.4
my settings:
![default](https://user-images.githubusercontent.com/23496061/52843376-e289ef00-313c-11e9-8f29-91851735e87e.png)

my tasks:

```

@shared_task(bind=True)
def hello(self,num):
    for i in range(0,num):
        self.update_state(state="PROGRESS", meta={'progress': int((float(i) / num) * 100)})
    a = "哈哈"
    return a
```

![default](https://user-images.githubusercontent.com/23496061/52843246-87f09300-313c-11e9-864b-fd0bedad9bd2.png)

I want to get result 哈哈 ,but it seems unicode。what should i do。Thank you very much。

**Comment by liquidpele** [comment]
If you find a way to make it appear correctly without breaking other encoding types (e.g. binary) then please send us a PR!

**Comment by devwon** [comment]
korean messy too..

**Comment by auvipy** [comment]
you should encoe them properly.

**Comment by nianqinianyi** [comment]
I had the same issue.
After researching, it seems that Celery uses the default parameters when saving results, meaning `json.dumps` uses the default value for `ensure_ascii`, which is `True`. 
I'm not sure if Celery has any parameters to set the default value for `ensure_ascii`. 
However, I resolved this issue by customizing the JSON serializer.

```python
import json
import os

from celery import Celery
from kombu.serialization import register


def json_serializer(data):
    # 解决中文被unicode编码的问题
    return json.dumps(data, ensure_ascii=False)


def json_deserializer(data):
    return json.loads(data)


register('json', json_serializer, json_deserializer, 'application/json')

# 设置 Django 的默认设置模块
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'my_project.settings')

app = Celery('my_project')

# 使用与 Django 设置相同的配置文件
app.config_from_object('django.conf:settings', namespace='CELERY')
```
