### ISSUE TITLE
Need info about the structure of the project

### ISSUE THREAD

**Issue by ajaykmr2292** [celery/django-celery-results#90]
Can you explain in plain terms how the project works? I mean specifically how are the task status, date_done etc. obtained from the celery? Please explain the flow if possible.
PS: I am new to Django. So, I cant understand the how celery contacts the backend to save results.

**Comment by ajaykmr2292** [comment]
And also please tell me the difference between `django_celery_results` and `django_celery_monitor` since I feel both can capture the task states. Celery monitor could even capture the runtime (which is not possible with celery results).

**Comment by ajaykmr2292** [comment]
Can I know whether I can find the structure of the project (to understand various components involved and their role like kombu etc.)?

**Comment by liquidpele** [comment]
All the code and docs are online.  If it's not there, then it's not documented.  

django_celery_monitor is not created by our team, so there is overlapping functionality.  Use whatever works best for you, or if you want to add functionality to django-celery-results please send us pull requests.  Cheers.
